# Generated by Django 5.1.5 on 2025-11-02 22:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bybit', 'Bybit')], default='bybit', max_length=50, verbose_name='Название биржи')),
                ('api_key_encrypted', models.BinaryField(verbose_name='Зашифрованный API ключ')),
                ('api_secret_encrypted', models.BinaryField(verbose_name='Зашифрованный API секрет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_testnet', models.BooleanField(default=True, verbose_name='Тестовая сеть')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Символ')),
                ('side', models.CharField(choices=[('long', 'LONG'), ('short', 'SHORT')], max_length=10, verbose_name='Направление')),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Цена входа')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Цена выхода')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Количество')),
                ('leverage', models.IntegerField(verbose_name='Плечо')),
                ('stop_loss', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Стоп-лосс')),
                ('take_profit', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Тейк-профит')),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PnL ($)')),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='PnL (%)')),
                ('order_id', models.CharField(blank=True, max_length=100, verbose_name='ID ордера')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='open', max_length=10, verbose_name='Статус')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Время открытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('notes', models.TextField(blank=True, help_text='Причина открытия/закрытия позиции', verbose_name='Заметки')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trading_strategy.exchange', verbose_name='Биржа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Всего сделок')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='Прибыльных сделок')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='Убыточных сделок')),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общий PnL ($)')),
                ('total_pnl_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Общий PnL (%)')),
                ('average_win', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Средняя прибыль ($)')),
                ('average_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Средний убыток ($)')),
                ('max_win', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Максимальная прибыль ($)')),
                ('max_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Максимальный убыток ($)')),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Максимальная просадка ($)')),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Винрейт (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_stats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика торговли',
                'verbose_name_plural': 'Статистика торговли',
            },
        ),
        migrations.CreateModel(
            name='UserTradingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_order_size', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Размер позиции в долларах', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Базовый размер ордера ($)')),
                ('leverage', models.IntegerField(default=10, help_text='Размер плеча (1-100x)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Плечо')),
                ('risk_per_trade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Процент от депозита, который рискуете на одной сделке', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Риск на сделку (%)')),
                ('timeframe', models.CharField(default='5m', help_text='Таймфрейм для анализа (зашит в стратегии)', max_length=10, verbose_name='Таймфрейм')),
                ('ema_fast_period', models.IntegerField(default=9, verbose_name='Период быстрой EMA')),
                ('ema_slow_period', models.IntegerField(default=21, verbose_name='Период медленной EMA')),
                ('rsi_period', models.IntegerField(default=14, verbose_name='Период RSI')),
                ('williams_r_period', models.IntegerField(default=14, verbose_name='Период Williams %R')),
                ('channel_period', models.IntegerField(default=20, verbose_name='Период канала (свечей)')),
                ('atr_period', models.IntegerField(default=14, verbose_name='Период ATR')),
                ('stop_loss_atr_multiplier', models.DecimalField(decimal_places=1, default=Decimal('1.5'), max_digits=3, verbose_name='Множитель ATR для стоп-лосса')),
                ('take_profit_atr_multiplier', models.DecimalField(decimal_places=1, default=Decimal('2.5'), max_digits=3, verbose_name='Множитель ATR для тейк-профита')),
                ('is_trading_active', models.BooleanField(default=False, verbose_name='Торговля активна')),
                ('is_test_mode', models.BooleanField(default=False, help_text='Если True, сигналы отправляются как уведомления без реальных сделок', verbose_name='Тестовый режим')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки торговли',
                'verbose_name_plural': 'Настройки торговли',
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Например: BTCUSDT', max_length=20, verbose_name='Символ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_pairs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Торговая пара',
                'verbose_name_plural': 'Торговые пары',
                'ordering': ['symbol'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
