# Generated by Django 5.1.5 on 2025-11-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_strategy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Символ')),
                ('signal', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=10, verbose_name='Направление')),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Цена входа')),
                ('stop_loss', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Стоп-лосс')),
                ('take_profit', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Тейк-профит')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Уверенность (%)')),
                ('reason', models.TextField(blank=True, verbose_name='Причина сигнала')),
                ('was_opened', models.BooleanField(default=False, verbose_name='Позиция была открыта')),
                ('was_profitable', models.BooleanField(blank=True, null=True, verbose_name='Прибыльная сделка')),
                ('actual_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактический PnL')),
                ('ema9', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='EMA9')),
                ('ema21', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='EMA21')),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='RSI')),
                ('williams_r', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Williams %R')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время сигнала')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История сигналов',
                'verbose_name_plural': 'История сигналов',
                'ordering': ['-created_at'],
            },
        ),
    ]
