# Generated by Django 5.1.5 on 2025-11-03 16:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_strategy', '0003_usertradingsettings_stop_loss_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertradingsettings',
            name='stop_loss_percent',
        ),
        migrations.RemoveField(
            model_name='usertradingsettings',
            name='take_profit_percent',
        ),
        migrations.AddField(
            model_name='usertradingsettings',
            name='strategy_name',
            field=models.CharField(default='main', help_text='Название используемой стратегии', max_length=50, verbose_name='Стратегия'),
        ),
        migrations.AlterField(
            model_name='usertradingsettings',
            name='stop_loss_atr_multiplier',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.5'), max_digits=3, verbose_name='Множитель ATR для стоп-лосса'),
        ),
        migrations.AlterField(
            model_name='usertradingsettings',
            name='take_profit_atr_multiplier',
            field=models.DecimalField(decimal_places=1, default=Decimal('2.5'), max_digits=3, verbose_name='Множитель ATR для тейк-профита'),
        ),
    ]
