# Generated by Django 5.1.5 on 2025-11-03 16:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_strategy', '0004_remove_usertradingsettings_stop_loss_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradingsettings',
            name='stop_loss_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Стоп-лосс (% от цены входа)'),
        ),
        migrations.AddField(
            model_name='usertradingsettings',
            name='take_profit_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=5, verbose_name='Тейк-профит (% от цены входа)'),
        ),
        migrations.AlterField(
            model_name='usertradingsettings',
            name='stop_loss_atr_multiplier',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.5'), max_digits=3, verbose_name='[DEPRECATED] Множитель ATR для стоп-лосса'),
        ),
        migrations.AlterField(
            model_name='usertradingsettings',
            name='take_profit_atr_multiplier',
            field=models.DecimalField(decimal_places=1, default=Decimal('2.5'), max_digits=3, verbose_name='[DEPRECATED] Множитель ATR для тейк-профита'),
        ),
    ]
