# Generated by Django 5.1.5 on 2026-02-12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_strategy', '0005_usertradingsettings_stop_loss_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradingsettings',
            name='order_size_mode',
            field=models.CharField(
                choices=[
                    ('fixed_usd', 'Фиксированный размер ($)'),
                    ('percent_balance', 'Процент от депозита (%)'),
                ],
                default='fixed_usd',
                help_text='Фиксированная сумма в $ или процент от свободного баланса USDT',
                max_length=20,
                verbose_name='Режим размера ордера',
            ),
        ),
        migrations.AddField(
            model_name='usertradingsettings',
            name='order_size_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('1.00'),
                help_text='Используется при режиме "Процент от депозита"',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.10')),
                    django.core.validators.MaxValueValidator(Decimal('100.00')),
                ],
                verbose_name='Размер ордера (% от депозита)',
            ),
        ),
    ]
