# Generated by Django 5.1.5 on 2026-02-12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_strategy', '0006_usertradingsettings_order_size_mode_and_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradingsettings',
            name='auto_pause_on_risk',
            field=models.BooleanField(
                default=True,
                help_text='Если включено, бот останавливает торговлю при срабатывании лимитов',
                verbose_name='Автопауза по рискам',
            ),
        ),
        migrations.AddField(
            model_name='usertradingsettings',
            name='daily_loss_limit_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('3.00'),
                help_text='При достижении этого лимита торговля автоматически ставится на паузу',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.10')),
                    django.core.validators.MaxValueValidator(Decimal('100.00')),
                ],
                verbose_name='Дневной лимит убытка (%)',
            ),
        ),
        migrations.AddField(
            model_name='usertradingsettings',
            name='is_risk_paused',
            field=models.BooleanField(default=False, verbose_name='Пауза по рискам'),
        ),
        migrations.AddField(
            model_name='usertradingsettings',
            name='max_consecutive_losses',
            field=models.IntegerField(
                default=3,
                help_text='После N убыточных сделок подряд торговля автоматически ставится на паузу',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name='Максимум убыточных подряд',
            ),
        ),
        migrations.AddField(
            model_name='usertradingsettings',
            name='risk_pause_reason',
            field=models.TextField(blank=True, verbose_name='Причина паузы по рискам'),
        ),
        migrations.AddField(
            model_name='usertradingsettings',
            name='risk_paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время паузы по рискам'),
        ),
    ]
